import React, { Component } from 'react';

export default class Record extends Component {
    render() {
        return (
            <div style={{ width: '80vw' }}>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam vitae sollicitudin libero, non ornare ligula. Vivamus in justo vel arcu aliquet rhoncus a eget ex. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras pulvinar augue lorem, in pretium lorem interdum in. Proin eros tortor, interdum id massa at, tincidunt dignissim neque. Nunc ac vehicula risus. Nullam efficitur nunc ex, eget finibus massa vestibulum vitae. Cras dui justo, ullamcorper ut fermentum vel, elementum in dolor. Ut cursus viverra enim, ac tempor nisi scelerisque quis. Praesent vestibulum, quam vestibulum consectetur sodales, ante erat lobortis felis, eget rutrum augue sem eget nunc. Quisque sit amet malesuada lectus. Pellentesque rutrum lorem a dolor auctor egestas. Cras vel urna sit amet lorem consequat posuere id at purus. Mauris a mauris eros. Cras imperdiet lacus sollicitudin placerat vehicula.

                Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur mollis est velit, sed pharetra augue dictum quis. Ut vel ipsum faucibus, laoreet lectus ac, pharetra magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean maximus massa mauris, ut congue felis maximus nec. Phasellus id augue tortor. Praesent interdum tristique tellus, vel dictum libero placerat id.

                Pellentesque non interdum mauris, non porta dolor. In eget ipsum vel arcu pulvinar scelerisque tincidunt eget ipsum. Integer ultrices, odio sed faucibus varius, enim neque rutrum neque, nec porttitor tellus dui nec ante. Integer posuere scelerisque odio at egestas. Nam ultricies vehicula molestie. Maecenas tristique egestas nunc, nec egestas diam gravida at. Cras mattis felis ut justo blandit malesuada. Maecenas tempor erat suscipit, suscipit elit at, placerat erat.

                Curabitur malesuada ipsum arcu, nec tristique metus feugiat a. In nec dictum libero, non sagittis mi. Sed vitae enim nisi. Sed finibus tortor eu efficitur lacinia. Quisque tristique nisi risus, in gravida ex lacinia vitae. Etiam lobortis, nulla eu vulputate dignissim, ante lorem tincidunt lectus, non efficitur ante nulla sed diam. Nulla felis diam, dapibus sit amet condimentum at, pulvinar eget ligula.

                Morbi ut pellentesque felis. Donec lacinia purus vel justo euismod pharetra. Fusce euismod ante ex, eget cursus risus tempus non. Donec aliquam nunc tortor, vitae efficitur ante scelerisque vel. Sed dolor mi, ullamcorper nec nulla tincidunt, consectetur fringilla sem. Aliquam vitae ante ligula. Nam commodo, ligula vitae tempus sodales, risus justo placerat purus, ac fermentum nunc enim vitae magna. Vestibulum tincidunt nisl lorem, eu tincidunt sapien placerat id. Vestibulum aliquam massa aliquam diam cursus, in tempus felis feugiat. Etiam et mauris leo. Ut tincidunt quis enim eu elementum. Phasellus dignissim lacus ornare, vestibulum odio in, eleifend mauris. Fusce interdum sollicitudin diam non porttitor. Donec ut iaculis erat. Suspendisse tellus dui, pulvinar nec placerat sed, volutpat sit amet arcu. Morbi non libero non est luctus sodales eu non dui.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam vitae sollicitudin libero, non ornare ligula. Vivamus in justo vel arcu aliquet rhoncus a eget ex. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras pulvinar augue lorem, in pretium lorem interdum in. Proin eros tortor, interdum id massa at, tincidunt dignissim neque. Nunc ac vehicula risus. Nullam efficitur nunc ex, eget finibus massa vestibulum vitae. Cras dui justo, ullamcorper ut fermentum vel, elementum in dolor. Ut cursus viverra enim, ac tempor nisi scelerisque quis. Praesent vestibulum, quam vestibulum consectetur sodales, ante erat lobortis felis, eget rutrum augue sem eget nunc. Quisque sit amet malesuada lectus. Pellentesque rutrum lorem a dolor auctor egestas. Cras vel urna sit amet lorem consequat posuere id at purus. Mauris a mauris eros. Cras imperdiet lacus sollicitudin placerat vehicula.

                Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur mollis est velit, sed pharetra augue dictum quis. Ut vel ipsum faucibus, laoreet lectus ac, pharetra magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean maximus massa mauris, ut congue felis maximus nec. Phasellus id augue tortor. Praesent interdum tristique tellus, vel dictum libero placerat id.

                Pellentesque non interdum mauris, non porta dolor. In eget ipsum vel arcu pulvinar scelerisque tincidunt eget ipsum. Integer ultrices, odio sed faucibus varius, enim neque rutrum neque, nec porttitor tellus dui nec ante. Integer posuere scelerisque odio at egestas. Nam ultricies vehicula molestie. Maecenas tristique egestas nunc, nec egestas diam gravida at. Cras mattis felis ut justo blandit malesuada. Maecenas tempor erat suscipit, suscipit elit at, placerat erat.

                Curabitur malesuada ipsum arcu, nec tristique metus feugiat a. In nec dictum libero, non sagittis mi. Sed vitae enim nisi. Sed finibus tortor eu efficitur lacinia. Quisque tristique nisi risus, in gravida ex lacinia vitae. Etiam lobortis, nulla eu vulputate dignissim, ante lorem tincidunt lectus, non efficitur ante nulla sed diam. Nulla felis diam, dapibus sit amet condimentum at, pulvinar eget ligula.

                Morbi ut pellentesque felis. Donec lacinia purus vel justo euismod pharetra. Fusce euismod ante ex, eget cursus risus tempus non. Donec aliquam nunc tortor, vitae efficitur ante scelerisque vel. Sed dolor mi, ullamcorper nec nulla tincidunt, consectetur fringilla sem. Aliquam vitae ante ligula. Nam commodo, ligula vitae tempus sodales, risus justo placerat purus, ac fermentum nunc enim vitae magna. Vestibulum tincidunt nisl lorem, eu tincidunt sapien placerat id. Vestibulum aliquam massa aliquam diam cursus, in tempus felis feugiat. Etiam et mauris leo. Ut tincidunt quis enim eu elementum. Phasellus dignissim lacus ornare, vestibulum odio in, eleifend mauris. Fusce interdum sollicitudin diam non porttitor. Donec ut iaculis erat. Suspendisse tellus dui, pulvinar nec placerat sed, volutpat sit amet arcu. Morbi non libero non est luctus sodales eu non dui.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam vitae sollicitudin libero, non ornare ligula. Vivamus in justo vel arcu aliquet rhoncus a eget ex. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras pulvinar augue lorem, in pretium lorem interdum in. Proin eros tortor, interdum id massa at, tincidunt dignissim neque. Nunc ac vehicula risus. Nullam efficitur nunc ex, eget finibus massa vestibulum vitae. Cras dui justo, ullamcorper ut fermentum vel, elementum in dolor. Ut cursus viverra enim, ac tempor nisi scelerisque quis. Praesent vestibulum, quam vestibulum consectetur sodales, ante erat lobortis felis, eget rutrum augue sem eget nunc. Quisque sit amet malesuada lectus. Pellentesque rutrum lorem a dolor auctor egestas. Cras vel urna sit amet lorem consequat posuere id at purus. Mauris a mauris eros. Cras imperdiet lacus sollicitudin placerat vehicula.

                Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur mollis est velit, sed pharetra augue dictum quis. Ut vel ipsum faucibus, laoreet lectus ac, pharetra magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean maximus massa mauris, ut congue felis maximus nec. Phasellus id augue tortor. Praesent interdum tristique tellus, vel dictum libero placerat id.

                Pellentesque non interdum mauris, non porta dolor. In eget ipsum vel arcu pulvinar scelerisque tincidunt eget ipsum. Integer ultrices, odio sed faucibus varius, enim neque rutrum neque, nec porttitor tellus dui nec ante. Integer posuere scelerisque odio at egestas. Nam ultricies vehicula molestie. Maecenas tristique egestas nunc, nec egestas diam gravida at. Cras mattis felis ut justo blandit malesuada. Maecenas tempor erat suscipit, suscipit elit at, placerat erat.

                Curabitur malesuada ipsum arcu, nec tristique metus feugiat a. In nec dictum libero, non sagittis mi. Sed vitae enim nisi. Sed finibus tortor eu efficitur lacinia. Quisque tristique nisi risus, in gravida ex lacinia vitae. Etiam lobortis, nulla eu vulputate dignissim, ante lorem tincidunt lectus, non efficitur ante nulla sed diam. Nulla felis diam, dapibus sit amet condimentum at, pulvinar eget ligula.

                Morbi ut pellentesque felis. Donec lacinia purus vel justo euismod pharetra. Fusce euismod ante ex, eget cursus risus tempus non. Donec aliquam nunc tortor, vitae efficitur ante scelerisque vel. Sed dolor mi, ullamcorper nec nulla tincidunt, consectetur fringilla sem. Aliquam vitae ante ligula. Nam commodo, ligula vitae tempus sodales, risus justo placerat purus, ac fermentum nunc enim vitae magna. Vestibulum tincidunt nisl lorem, eu tincidunt sapien placerat id. Vestibulum aliquam massa aliquam diam cursus, in tempus felis feugiat. Etiam et mauris leo. Ut tincidunt quis enim eu elementum. Phasellus dignissim lacus ornare, vestibulum odio in, eleifend mauris. Fusce interdum sollicitudin diam non porttitor. Donec ut iaculis erat. Suspendisse tellus dui, pulvinar nec placerat sed, volutpat sit amet arcu. Morbi non libero non est luctus sodales eu non dui.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam vitae sollicitudin libero, non ornare ligula. Vivamus in justo vel arcu aliquet rhoncus a eget ex. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras pulvinar augue lorem, in pretium lorem interdum in. Proin eros tortor, interdum id massa at, tincidunt dignissim neque. Nunc ac vehicula risus. Nullam efficitur nunc ex, eget finibus massa vestibulum vitae. Cras dui justo, ullamcorper ut fermentum vel, elementum in dolor. Ut cursus viverra enim, ac tempor nisi scelerisque quis. Praesent vestibulum, quam vestibulum consectetur sodales, ante erat lobortis felis, eget rutrum augue sem eget nunc. Quisque sit amet malesuada lectus. Pellentesque rutrum lorem a dolor auctor egestas. Cras vel urna sit amet lorem consequat posuere id at purus. Mauris a mauris eros. Cras imperdiet lacus sollicitudin placerat vehicula.

                Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur mollis est velit, sed pharetra augue dictum quis. Ut vel ipsum faucibus, laoreet lectus ac, pharetra magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean maximus massa mauris, ut congue felis maximus nec. Phasellus id augue tortor. Praesent interdum tristique tellus, vel dictum libero placerat id.

                Pellentesque non interdum mauris, non porta dolor. In eget ipsum vel arcu pulvinar scelerisque tincidunt eget ipsum. Integer ultrices, odio sed faucibus varius, enim neque rutrum neque, nec porttitor tellus dui nec ante. Integer posuere scelerisque odio at egestas. Nam ultricies vehicula molestie. Maecenas tristique egestas nunc, nec egestas diam gravida at. Cras mattis felis ut justo blandit malesuada. Maecenas tempor erat suscipit, suscipit elit at, placerat erat.

                Curabitur malesuada ipsum arcu, nec tristique metus feugiat a. In nec dictum libero, non sagittis mi. Sed vitae enim nisi. Sed finibus tortor eu efficitur lacinia. Quisque tristique nisi risus, in gravida ex lacinia vitae. Etiam lobortis, nulla eu vulputate dignissim, ante lorem tincidunt lectus, non efficitur ante nulla sed diam. Nulla felis diam, dapibus sit amet condimentum at, pulvinar eget ligula.

                Morbi ut pellentesque felis. Donec lacinia purus vel justo euismod pharetra. Fusce euismod ante ex, eget cursus risus tempus non. Donec aliquam nunc tortor, vitae efficitur ante scelerisque vel. Sed dolor mi, ullamcorper nec nulla tincidunt, consectetur fringilla sem. Aliquam vitae ante ligula. Nam commodo, ligula vitae tempus sodales, risus justo placerat purus, ac fermentum nunc enim vitae magna. Vestibulum tincidunt nisl lorem, eu tincidunt sapien placerat id. Vestibulum aliquam massa aliquam diam cursus, in tempus felis feugiat. Etiam et mauris leo. Ut tincidunt quis enim eu elementum. Phasellus dignissim lacus ornare, vestibulum odio in, eleifend mauris. Fusce interdum sollicitudin diam non porttitor. Donec ut iaculis erat. Suspendisse tellus dui, pulvinar nec placerat sed, volutpat sit amet arcu. Morbi non libero non est luctus sodales eu non dui.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam vitae sollicitudin libero, non ornare ligula. Vivamus in justo vel arcu aliquet rhoncus a eget ex. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras pulvinar augue lorem, in pretium lorem interdum in. Proin eros tortor, interdum id massa at, tincidunt dignissim neque. Nunc ac vehicula risus. Nullam efficitur nunc ex, eget finibus massa vestibulum vitae. Cras dui justo, ullamcorper ut fermentum vel, elementum in dolor. Ut cursus viverra enim, ac tempor nisi scelerisque quis. Praesent vestibulum, quam vestibulum consectetur sodales, ante erat lobortis felis, eget rutrum augue sem eget nunc. Quisque sit amet malesuada lectus. Pellentesque rutrum lorem a dolor auctor egestas. Cras vel urna sit amet lorem consequat posuere id at purus. Mauris a mauris eros. Cras imperdiet lacus sollicitudin placerat vehicula.

                Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur mollis est velit, sed pharetra augue dictum quis. Ut vel ipsum faucibus, laoreet lectus ac, pharetra magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean maximus massa mauris, ut congue felis maximus nec. Phasellus id augue tortor. Praesent interdum tristique tellus, vel dictum libero placerat id.

                Pellentesque non interdum mauris, non porta dolor. In eget ipsum vel arcu pulvinar scelerisque tincidunt eget ipsum. Integer ultrices, odio sed faucibus varius, enim neque rutrum neque, nec porttitor tellus dui nec ante. Integer posuere scelerisque odio at egestas. Nam ultricies vehicula molestie. Maecenas tristique egestas nunc, nec egestas diam gravida at. Cras mattis felis ut justo blandit malesuada. Maecenas tempor erat suscipit, suscipit elit at, placerat erat.

                Curabitur malesuada ipsum arcu, nec tristique metus feugiat a. In nec dictum libero, non sagittis mi. Sed vitae enim nisi. Sed finibus tortor eu efficitur lacinia. Quisque tristique nisi risus, in gravida ex lacinia vitae. Etiam lobortis, nulla eu vulputate dignissim, ante lorem tincidunt lectus, non efficitur ante nulla sed diam. Nulla felis diam, dapibus sit amet condimentum at, pulvinar eget ligula.

                Morbi ut pellentesque felis. Donec lacinia purus vel justo euismod pharetra. Fusce euismod ante ex, eget cursus risus tempus non. Donec aliquam nunc tortor, vitae efficitur ante scelerisque vel. Sed dolor mi, ullamcorper nec nulla tincidunt, consectetur fringilla sem. Aliquam vitae ante ligula. Nam commodo, ligula vitae tempus sodales, risus justo placerat purus, ac fermentum nunc enim vitae magna. Vestibulum tincidunt nisl lorem, eu tincidunt sapien placerat id. Vestibulum aliquam massa aliquam diam cursus, in tempus felis feugiat. Etiam et mauris leo. Ut tincidunt quis enim eu elementum. Phasellus dignissim lacus ornare, vestibulum odio in, eleifend mauris. Fusce interdum sollicitudin diam non porttitor. Donec ut iaculis erat. Suspendisse tellus dui, pulvinar nec placerat sed, volutpat sit amet arcu. Morbi non libero non est luctus sodales eu non dui.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam vitae sollicitudin libero, non ornare ligula. Vivamus in justo vel arcu aliquet rhoncus a eget ex. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras pulvinar augue lorem, in pretium lorem interdum in. Proin eros tortor, interdum id massa at, tincidunt dignissim neque. Nunc ac vehicula risus. Nullam efficitur nunc ex, eget finibus massa vestibulum vitae. Cras dui justo, ullamcorper ut fermentum vel, elementum in dolor. Ut cursus viverra enim, ac tempor nisi scelerisque quis. Praesent vestibulum, quam vestibulum consectetur sodales, ante erat lobortis felis, eget rutrum augue sem eget nunc. Quisque sit amet malesuada lectus. Pellentesque rutrum lorem a dolor auctor egestas. Cras vel urna sit amet lorem consequat posuere id at purus. Mauris a mauris eros. Cras imperdiet lacus sollicitudin placerat vehicula.

                Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur mollis est velit, sed pharetra augue dictum quis. Ut vel ipsum faucibus, laoreet lectus ac, pharetra magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean maximus massa mauris, ut congue felis maximus nec. Phasellus id augue tortor. Praesent interdum tristique tellus, vel dictum libero placerat id.

                Pellentesque non interdum mauris, non porta dolor. In eget ipsum vel arcu pulvinar scelerisque tincidunt eget ipsum. Integer ultrices, odio sed faucibus varius, enim neque rutrum neque, nec porttitor tellus dui nec ante. Integer posuere scelerisque odio at egestas. Nam ultricies vehicula molestie. Maecenas tristique egestas nunc, nec egestas diam gravida at. Cras mattis felis ut justo blandit malesuada. Maecenas tempor erat suscipit, suscipit elit at, placerat erat.

                Curabitur malesuada ipsum arcu, nec tristique metus feugiat a. In nec dictum libero, non sagittis mi. Sed vitae enim nisi. Sed finibus tortor eu efficitur lacinia. Quisque tristique nisi risus, in gravida ex lacinia vitae. Etiam lobortis, nulla eu vulputate dignissim, ante lorem tincidunt lectus, non efficitur ante nulla sed diam. Nulla felis diam, dapibus sit amet condimentum at, pulvinar eget ligula.

Morbi ut pellentesque felis. Donec lacinia purus vel justo euismod pharetra. Fusce euismod ante ex, eget cursus risus tempus non. Donec aliquam nunc tortor, vitae efficitur ante scelerisque vel. Sed dolor mi, ullamcorper nec nulla tincidunt, consectetur fringilla sem. Aliquam vitae ante ligula. Nam commodo, ligula vitae tempus sodales, risus justo placerat purus, ac fermentum nunc enim vitae magna. Vestibulum tincidunt nisl lorem, eu tincidunt sapien placerat id. Vestibulum aliquam massa aliquam diam cursus, in tempus felis feugiat. Etiam et mauris leo. Ut tincidunt quis enim eu elementum. Phasellus dignissim lacus ornare, vestibulum odio in, eleifend mauris. Fusce interdum sollicitudin diam non porttitor. Donec ut iaculis erat. Suspendisse tellus dui, pulvinar nec placerat sed, volutpat sit amet arcu. Morbi non libero non est luctus sodales eu non dui.</p>
            </div>
        );
    }
}